/** Achievement badges — broader than style unlock challenges. */

export const ACHIEVEMENTS = [
  { id: 'first_death', title: 'Learning Curve', desc: 'Die once.', category: 'milestones' },
  { id: 'first_clear', title: 'Sector One', desc: 'Clear your first sector.', category: 'milestones' },
  { id: 'clears_10', title: 'Veteran', desc: 'Clear 10 sectors total.', category: 'milestones', counter: 'lifetimeClears', target: 10 },
  { id: 'clears_25', title: 'Regular', desc: 'Clear 25 sectors total.', category: 'milestones', counter: 'lifetimeClears', target: 25 },
  { id: 'clears_50', title: 'War Machine', desc: 'Clear 50 sectors total.', category: 'milestones', counter: 'lifetimeClears', target: 50 },
  { id: 'clears_100', title: 'Sector Grinder', desc: 'Clear 100 sectors total.', category: 'milestones', counter: 'lifetimeClears', target: 100 },
  { id: 'deaths_10', title: 'Stubborn', desc: 'Die 10 times.', category: 'milestones', counter: 'lifetimeDeaths', target: 10 },
  { id: 'deaths_25', title: 'Persistent', desc: 'Die 25 times.', category: 'milestones', counter: 'lifetimeDeaths', target: 25 },
  { id: 'deaths_50', title: 'Unbreakable Spirit', desc: 'Die 50 times.', category: 'milestones', counter: 'lifetimeDeaths', target: 50 },
  { id: 'weave_master', title: 'Weave Master', desc: '20 perfect weaves in one run.', category: 'skill', flag: 'run_perfects_20' },
  { id: 'weave_30_run', title: 'Weave Storm', desc: '30 perfect weaves in one run.', category: 'skill', flag: 'run_perfects_30' },
  { id: 'no_dash_clear', title: 'Purist', desc: 'Clear a sector without dashing.', category: 'skill', flag: 'no_dash_clear' },
  { id: 'chain_5', title: 'Chain Reaction', desc: 'Reach chain ×5 in one sector.', category: 'skill', flag: 'chain_5' },
  { id: 'chain_10', title: 'Unbroken', desc: 'Reach chain ×10 in one sector.', category: 'skill', flag: 'chain_10' },
  { id: 'chain_15', title: 'Relentless', desc: 'Reach chain ×15 in one sector.', category: 'skill', flag: 'chain_15' },
  { id: 'grade_s_3', title: 'Triple S', desc: 'Earn S rank on 3 different sectors.', category: 'grades', counter: 's_grades', target: 3 },
  { id: 'grade_s_5', title: 'Five Star', desc: 'Earn S rank on 5 different sectors.', category: 'grades', counter: 's_grades', target: 5 },
  { id: 'grade_s_all', title: 'Perfectionist', desc: 'Earn S rank on every sector.', category: 'grades', counter: 's_grades', target: 10 },
  { id: 'endless_3', title: 'Wave Rider', desc: 'Survive 3 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 3 },
  { id: 'endless_5', title: 'Endless Five', desc: 'Survive 5 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 5 },
  { id: 'endless_10', title: 'Endless Ten', desc: 'Survive 10 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 10 },
  { id: 'endless_15', title: 'Deep End', desc: 'Survive 15 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 15 },
  { id: 'endless_20', title: 'Abyss Walker', desc: 'Survive 20 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 20 },
  { id: 'endless_30', title: 'Void Runner', desc: 'Survive 30 endless waves.', category: 'endless', counter: 'bestEndlessWave', target: 30 },
  { id: 'campaign_clear', title: 'Rupture Cleared', desc: 'Beat sector 10 in Classic.', category: 'campaign', flag: 'campaign_complete' },
  { id: 'ng_plus_clear', title: 'New Game+', desc: 'Clear any sector in New Game+.', category: 'campaign', flag: 'ng_plus_clear' },
  { id: 'styles_2', title: 'Dual Wield', desc: 'Own 2 combat styles.', category: 'styles', counter: 'ownedStyles', target: 2 },
  { id: 'styles_3', title: 'Arsenal', desc: 'Own 3 combat styles.', category: 'styles', counter: 'ownedStyles', target: 3 },
  { id: 'styles_5', title: 'Style Collector', desc: 'Own 5 combat styles.', category: 'styles', counter: 'ownedStyles', target: 5 },
  { id: 'styles_all', title: 'Full Kit', desc: 'Unlock every combat style.', category: 'styles', counter: 'ownedStyles', target: 6 },
  { id: 'style_linear_5', title: 'Linear Pro', desc: '5 clears with Linear Sniper.', category: 'styles', counter: 'style_linear_clears', target: 5 },
  { id: 'style_linear_10', title: 'Linear Ace', desc: '10 clears with Linear Sniper.', category: 'styles', counter: 'style_linear_clears', target: 10 },
  { id: 'style_pulse_5', title: 'Pulse Breaker', desc: '5 clears with Pulse Breaker.', category: 'styles', counter: 'style_pulse_clears', target: 5 },
  { id: 'style_phase_5', title: 'Phase Shift', desc: '5 clears with Phase Runner.', category: 'styles', counter: 'style_phase_clears', target: 5 },
  { id: 'style_arc_5', title: 'Arc Artist', desc: '5 clears with Arc Scatter.', category: 'styles', counter: 'style_arc_clears', target: 5 },
  { id: 'style_null_5', title: 'Null Field', desc: '5 clears with Null Suppressor.', category: 'styles', counter: 'style_null_clears', target: 5 },
  { id: 'style_overclock_5', title: 'Overclocked', desc: '5 clears with Overclock.', category: 'styles', counter: 'style_overclock_clears', target: 5 },
  { id: 'style_overclock_10', title: 'Max Clock', desc: '10 clears with Overclock.', category: 'styles', counter: 'style_overclock_clears', target: 10 },
  { id: 'credits_100', title: 'Pocket Change', desc: 'Bank 100 Weave Coins.', category: 'economy', counter: 'credits', target: 100 },
  { id: 'credits_500', title: 'Hoarder', desc: 'Bank 500 Weave Coins.', category: 'economy', counter: 'credits', target: 500 },
  { id: 'credits_1000', title: 'WC Baron', desc: 'Bank 1000 Weave Coins.', category: 'economy', counter: 'credits', target: 1000 },
  { id: 'daily_3', title: 'Three Day Streak', desc: 'Complete daily challenges 3 days in a row.', category: 'daily', counter: 'dailyStreak', target: 3 },
  { id: 'daily_7', title: 'Weekly Devotion', desc: 'Complete daily challenges 7 days in a row.', category: 'daily', counter: 'dailyStreak', target: 7 },
  { id: 'daily_14', title: 'Fortnight Focus', desc: 'Complete daily challenges 14 days in a row.', category: 'daily', counter: 'dailyStreak', target: 14 },
  { id: 'perfects_50', title: 'Half Century', desc: '50 lifetime perfect weaves.', category: 'skill', counter: 'lifetimePerfects', target: 50 },
  { id: 'perfects_100', title: 'Century Weave', desc: '100 lifetime perfect weaves.', category: 'skill', counter: 'lifetimePerfects', target: 100 },
  { id: 'perfects_250', title: 'Weave Legend', desc: '250 lifetime perfect weaves.', category: 'skill', counter: 'lifetimePerfects', target: 250 },
  { id: 'kills_50', title: 'Exterminator', desc: '50 enemy kills in one run.', category: 'skill', flag: 'run_kills_50' },
  { id: 'kills_100', title: 'Annihilator', desc: '100 enemy kills in one run.', category: 'skill', flag: 'run_kills_100' },
  { id: 'sector_1_s', title: 'Drift Master', desc: 'S rank on sector 1 — DRIFT.', category: 'grades', flag: 'sector_1_s' },
  { id: 'sector_5_s', title: 'Burst Master', desc: 'S rank on sector 5 — BURST.', category: 'grades', flag: 'sector_5_s' },
  { id: 'sector_10_s', title: 'Rupture Master', desc: 'S rank on sector 10 — RUPTURE.', category: 'grades', flag: 'sector_10_s' },
  { id: 'elite_kill_5', title: 'Elite Slayer', desc: 'Destroy 5 elite enemies.', category: 'combat', counter: 'eliteKills', target: 5 },
  { id: 'elite_kill_10', title: 'Elite Hunter', desc: 'Destroy 10 elite enemies.', category: 'combat', counter: 'eliteKills', target: 10 },
  { id: 'elite_kill_25', title: 'Elite Nemesis', desc: 'Destroy 25 elite enemies.', category: 'combat', counter: 'eliteKills', target: 25 },
  { id: 'challenge_3', title: 'On Assignment', desc: 'Complete 3 challenges.', category: 'milestones', counter: 'challengesDone', target: 3 },
  { id: 'challenge_5', title: 'Challenger', desc: 'Complete 5 challenges.', category: 'milestones', counter: 'challengesDone', target: 5 },
  { id: 'challenge_all', title: 'Challenge Master', desc: 'Complete every challenge.', category: 'milestones', counter: 'challengesDone', target: 9 },
  { id: 'achievements_10', title: 'Badge Hunter', desc: 'Earn 10 achievements.', category: 'milestones', counter: 'achievementsDone', target: 10 },
  { id: 'achievements_25', title: 'Trophy Case', desc: 'Earn 25 achievements.', category: 'milestones', counter: 'achievementsDone', target: 25 },
  { id: 'achievements_40', title: 'Hall of Fame', desc: 'Earn 40 achievements.', category: 'milestones', counter: 'achievementsDone', target: 40 },
  { id: 'mastery_any_3', title: 'Style Student', desc: 'Reach mastery level 3 with any style.', category: 'styles', flag: 'mastery_3' },
  { id: 'mastery_any_5', title: 'Style Master', desc: 'Reach mastery level 5 with any style.', category: 'styles', flag: 'mastery_5' },
  { id: 'boss_kill', title: 'Core Breach', desc: 'Destroy the RUPTURE core boss.', category: 'combat', flag: 'boss_kill' },
  { id: 'endless_mutator', title: 'Mutator Survived', desc: 'Clear an endless wave with an active mutator.', category: 'endless', flag: 'endless_mutator_clear' },
];

export const ACHIEVEMENT_BY_ID = Object.fromEntries(ACHIEVEMENTS.map((a) => [a.id, a]));

export const ACHIEVEMENT_CATEGORIES = [
  { id: 'milestones', label: 'Milestones' },
  { id: 'skill', label: 'Skill' },
  { id: 'grades', label: 'Grades' },
  { id: 'endless', label: 'Endless' },
  { id: 'campaign', label: 'Campaign' },
  { id: 'styles', label: 'Styles' },
  { id: 'economy', label: 'Economy' },
  { id: 'daily', label: 'Daily' },
  { id: 'combat', label: 'Combat' },
];
